const items = Object.freeze([
    {
        id: 1,
        book_name: "Gulliver's Travel 1",
        quantity: "1",
        total: "$60",
        borrowId: "#0123456",
        price: "$60",
        status: "Borrowing",
        rentFee: "10$",
        booksLeft: "4",
        description:
            "There are many variations of passages of Lorem Ipsum available, but the majority have suffered lebmid alteration in some ledmid form There are many variations of passages of Lorem Ipsum available ",
        language: "English",
        book_author: "Johnathan Swift",
        category: "Novel",
        department: "Comic Department",
        publication_date: "17/2/1999",
    },
    {
        id: 2,
        book_name: "Gulliver's Travel 2",
        quantity: "1",
        total: "$60",
        borrowId: "#0123456",
        price: "$60",
        status: "Borrowing",
        rentFee: "19$",
        booksLeft: "4",
        description:
            "There are many variations of passages of Lorem Ipsum available, but the majority have suffered lebmid alteration in some ledmid form There are many variations of passages of Lorem Ipsum available ",
        language: "English",
        book_author: "Johnathan Swift",
        category: "Novel",
        department: "Comic Department",
        publication_date: "17/2/1999",
    },
    {
        id: 3,
        book_name: "Gulliver's Travel 3",
        quantity: "1",
        total: "$60",
        borrowId: "#0123456",
        price: "$60",
        status: "Borrowing",
        rentFee: "1$",
        booksLeft: "4",
        description:
            "There are many variations of passages of Lorem Ipsum available, but the majority have suffered lebmid alteration in some ledmid form There are many variations of passages of Lorem Ipsum available ",
        language: "English",
        book_author: "Johnathan Swift",
        category: "Novel",
        department: "Comic Department",
        publication_date: "17/2/1999",
    },
    {
        id: 4,
        book_name: "Gulliver's Travel 4",
        quantity: "1",
        total: "$60",
        borrowId: "#0123456",
        price: "$60",
        status: "Borrowing",
        rentFee: "14$",
        booksLeft: "4",
        description:
            "There are many variations of passages of Lorem Ipsum available, but the majority have suffered lebmid alteration in some ledmid form There are many variations of passages of Lorem Ipsum available ",
        language: "English",
        book_author: "Johnathan Swift",
        category: "Novel",
        department: "Comic Department",

        publication_date: "17/2/1999",
    },
    {
        id: 5,
        book_name: "Gulliver's Travel 5",
        quantity: "1",
        total: "$60",
        borrowId: "#0123456",
        price: "$60",
        status: "Borrowing",
        rentFee: "17$",
        booksLeft: "4",
        description:
            "There are many variations of passages of Lorem Ipsum available, but the majority have suffered lebmid alteration in some ledmid form There are many variations of passages of Lorem Ipsum available ",
        language: "English",
        book_author: "Johnathan Swift",
        category: "Novel",
        department: "Comic Department",

        publication_date: "17/2/1999",
    },
    {
        id: 6,
        book_name: "Gulliver's Travel 6",
        quantity: "1",
        total: "$60",
        borrowId: "#0123456",
        price: "$60",
        status: "Borrowing",
        rentFee: "15$",
        booksLeft: "4",
        description:
            "There are many variations of passages of Lorem Ipsum available, but the majority have suffered lebmid alteration in some ledmid form There are many variations of passages of Lorem Ipsum available ",
        language: "English",
        book_author: "Johnathan Swift",
        category: "Novel",
        department: "Comic Department",
        publication_date: "17/2/1999",
    }
])
export default items
