const items = [
    {
        id: 1,
        book_name: "Gulliver's Travel",
        quantity: "1",
        total: "$60",
        borrowId: "#0123456",
        price: "$60",
        status: "Borrowing",
        rentFee: "10$",
    },
    {
        id: 2,
        book_name: "Gulliver's Travel",
        quantity: "1",
        total: "$60",
        borrowId: "#0123456",
        price: "$60",
        status: "Borrowing",
        rentFee: "10$",
    },
    {
        id: 3,
        book_name: "Gulliver's Travel",
        quantity: "1",
        total: "$60",
        borrowId: "#0123456",
        price: "$60",
        status: "Borrowing",
        rentFee: "10$",
    },
    {
        id: 4,
        book_name: "Gulliver's Travel",
        quantity: "1",
        total: "$60",
        borrowId: "#0123456",
        price: "$60",
        status: "Borrowing",
        rentFee: "10$",
    },
    {
        id: 5,
        book_name: "Gulliver's Travel",
        quantity: "1",
        total: "$60",
        borrowId: "#0123456",
        price: "$60",
        status: "Borrowing",
        rentFee: "10$",
    },
    {
        id: 6,
        book_name: "Gulliver's Travel",
        quantity: "1",
        total: "$60",
        borrowId: "#0123456",
        price: "$60",
        status: "Borrowing",
        rentFee: "10$",
    }
]
export default items